In [1]:
# 1)
import numpy as np

In [2]:
# 2) create 10 zeroes
a=np.zeros((1,10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [3]:
# 3) create a vector with values ranging from 10 to 100
vector=np.arange(10, 100)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [16]:
# 4) reverse it
print(f'Vectorul inversat este: {vector[::-1]}')

Vectorul inversat este: [99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [5]:
#5) reshape it to a 3x30
Matrice = vector.reshape(3,30)
print(Matrice)

[[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
  34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63
  64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93
  94 95 96 97 98 99]]


In [6]:
#6) Create the vector with elems 1,2,9,0,0,1,4,0. Find indices of non-zero elems.
vector_nou=[1, 2, 9, 0, 0, 1, 4, 0];
for i in range(len(vector_nou)):
    if vector_nou[i] == 0:
        print(f' Avem zero pe pozitia {i}')

 Avem zero pe pozitia 3
 Avem zero pe pozitia 4
 Avem zero pe pozitia 7


In [7]:
#7) Create a 3x3 identity matrix
identitatea = np.eye(3)
print(f'Matricea identitate: {identitatea}')

Matricea identitate: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
#8) Create a random vector of size 50 with values uniformely distributed in (-1, 1). Find the average of these values.
s= np.random.uniform(-1,1,50)
suma=sum(s);
print(s)
print(f'Media elementelor este {suma/50}')

[-0.15936195 -0.23422051 -0.07750447 -0.8196091   0.45184414 -0.59077217
 -0.35360292 -0.92427562 -0.05083398  0.79005267 -0.07611136 -0.01531824
 -0.67103651  0.86112639  0.00807534  0.44254435  0.02257431  0.20408653
  0.71317735  0.53737332  0.27237805 -0.04706638  0.48698041  0.56673269
  0.63746706  0.73808036  0.7786724  -0.90035895 -0.47633803  0.79265124
  0.28559286 -0.28044771  0.70782742  0.02758442 -0.57901711 -0.86505673
 -0.13696478 -0.59726845 -0.01453526 -0.19758113 -0.175825    0.72046996
 -0.74064327 -0.60534582  0.33794098 -0.11020164 -0.48454848  0.73497976
 -0.57163318 -0.00126139]
Media elementelor este 0.0072294367358720635


In [9]:
#9) create a 5x5 matrix with 1,2,3,4 just below the 1st diag and 0 in rest.
C = np.diag(1+np.arange(4),k=1)
print(C)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [10]:
#10) Create a 5x3 matrix and a 3x4 one. Multiply them.
matricea_A=np.random.random((5,3))
matricea_B=np.random.random((3,4))
produsul_matricilor=np.dot(matricea_A,matricea_B)
print(f'Matricea A este: {matricea_A}')
print(f'Matricea B este :{matricea_B}')
print(f'A*B :{produsul_matricilor}')

Matricea A este: [[0.1708377  0.21587285 0.40923838]
 [0.73620214 0.69213395 0.49179141]
 [0.62078563 0.36073234 0.29818032]
 [0.50092855 0.07929077 0.07070068]
 [0.33639129 0.56765698 0.60469751]]
Matricea B este :[[0.99328471 0.83609682 0.47167617 0.01961556]
 [0.10990124 0.76558364 0.59689206 0.75356559]
 [0.38970158 0.81883828 0.93178975 0.64265343]]
A*B :[[0.35289601 0.64320563 0.59075699 0.42902388]
 [0.99897659 1.54812033 1.21862446 0.85206079]
 [0.77246314 1.03936913 0.78596942 0.47563915]
 [0.53383099 0.53742091 0.34948226 0.11501283]
 [0.6321701  1.21099405 1.06094863 0.8229762 ]]


In [11]:
#11) Using the previous matrix, extract a new one with just the integer part of the values. Find at least 4 methods of doing this.
convert1=np.array(produsul_matricilor ,int)
convert2=produsul_matricilor.astype(int)
convert3=np.int_(produsul_matricilor)
convert4=np.asarray(produsul_matricilor, dtype=int)
print(f'Metoda 1: {convert1}')
print(f'Metoda 2: {convert2}')
print(f'Metoda 3: {convert3}')
print(f'Metoda 4: {convert4}')

Metoda 1: [[0 0 0 0]
 [0 1 1 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 1 0]]
Metoda 2: [[0 0 0 0]
 [0 1 1 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 1 0]]
Metoda 3: [[0 0 0 0]
 [0 1 1 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 1 0]]
Metoda 4: [[0 0 0 0]
 [0 1 1 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 1 0]]


In [12]:
#12) Create a random vector of size 25. Sort it.
random_vector=np.random.rand(25)
print(f'    Vectorul este :{random_vector}')
vectorul_sortat=np.sort(random_vector)
print(f'    Vectorul sortat este :{vectorul_sortat}')

    Vectorul este :[0.18018104 0.9500055  0.60908914 0.57522863 0.79199937 0.38690009
 0.6927862  0.76836765 0.16834181 0.09569365 0.199531   0.69345695
 0.04301931 0.09440831 0.61829941 0.07270008 0.86635759 0.02127025
 0.39404684 0.33098542 0.87434027 0.72037573 0.15839441 0.27887527
 0.24703671]
    Vectorul sortat este :[0.02127025 0.04301931 0.07270008 0.09440831 0.09569365 0.15839441
 0.16834181 0.18018104 0.199531   0.24703671 0.27887527 0.33098542
 0.38690009 0.39404684 0.57522863 0.60908914 0.61829941 0.6927862
 0.69345695 0.72037573 0.76836765 0.79199937 0.86635759 0.87434027
 0.9500055 ]


In [13]:
#13) Create a random 7x2 matrix representing 7 2D points. Convert them to polar coordinates.
Z = np.random.random((7,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.60148719 1.24245131 0.78232003 0.59618983 0.28026261 0.39923522
 0.76504243]
[1.11325282 0.73162797 1.56075163 0.92192029 0.28564115 0.56898357
 0.19172829]


In [17]:
#14) Generate a 10x10 matrix. Generate a single random number. Find the number in the matrix closest to it.
import random
random_number=random.random()*100
vectorul_pentru_matrice1=np.arange(0,99)
vectorul_pentru_matrice2=np.append(vectorul_pentru_matrice1,random_number)
noua_matrice=vectorul_pentru_matrice2.reshape(10,10)
print(f'Matricea 10x10: {noua_matrice}')
closest_number=(np.abs(vectorul_pentru_matrice1-random_number)).argmin()    
print(f'Numarul cel mai apropiat de numarul aleator este: {closest_number}')    

Matricea 10x10: [[ 0.          1.          2.          3.          4.          5.
   6.          7.          8.          9.        ]
 [10.         11.         12.         13.         14.         15.
  16.         17.         18.         19.        ]
 [20.         21.         22.         23.         24.         25.
  26.         27.         28.         29.        ]
 [30.         31.         32.         33.         34.         35.
  36.         37.         38.         39.        ]
 [40.         41.         42.         43.         44.         45.
  46.         47.         48.         49.        ]
 [50.         51.         52.         53.         54.         55.
  56.         57.         58.         59.        ]
 [60.         61.         62.         63.         64.         65.
  66.         67.         68.         69.        ]
 [70.         71.         72.         73.         74.         75.
  76.         77.         78.         79.        ]
 [80.         81.         82.         83.       